### ISSUE TITLE
How to compile the examples like HelloPangolin?

### ISSUE THREAD

**Issue by yanzhenqiang** [FangGet/pangolin_android#1]

**Comment by FangGet** [comment]
when you compiled pangolin with android-cmake, examples will be compiled along with. It's generated inside your build directory

**Comment by yanzhenqiang** [comment]
thanks for your reply.  I can compile them to .so files.  but for examples in your baidu cloud, I do not know how to compile them to apk?

**Comment by FangGet** [comment]
the examples in my baidu cloud are Eclipse projects, you can use Eclipse to import it and run directly.

**Comment by yanzhenqiang** [comment]
I compile successfully.  thanks

**Comment by yuri4029** [comment]
@yanzhenqiang Can you tell me how to compile .so file ?
