### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by Edmospheric-pressure** [FangGet/pangolin_android#2]
I tried to compile your building steps in linux, but it is not working. I typed:
export ANDROID_NDK=~/Downloads/android-ndk-r12b
cd pangolin_android
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=../android-cmake/android.toolchain.cmake \
      -DANDROID_NDK=ANDROID_NDK                       \
      -DCMAKE_BUILD_TYPE=Release                     \
      -DANDROID_ABI="armeabi-v7a"          \
      -DANDROID_NATIVE_API_LEVEL=android-19          \
      <source_path>
 Then the terminal printed lots of things and the last few lines are 
-- Android Target: 
CMake Error at CMakeModules/AndroidUtils.cmake:129 (message):
  No Android SDK platforms found.  Please install an Android platform SDK.
  On Linux, run 'android'.

**Comment by FangGet** [comment]
-DANDROID_NDK=${ANDROID_NDK}, btw, source_path should be revised
