### ISSUE TITLE
Android arm64-v8a

### ISSUE THREAD

**Issue by fszeliga** [FangGet/pangolin_android#3]
Hey, I cant seem to compile this sucessfully for the newest 64-bit architecture. would you maybe be able to compile it and upload the compiled library or let me know how i can get it to work? any help is appreciated! thanks!

**Comment by FangGet** [comment]
I had never tried for 64bit, may try out tomorrow, then tell you the result

**Comment by FangGet** [comment]
I compiled arm64-v8a library successfully, just do the step as readme.md says while change ANDROID_ABI to arm64-v8a, everything will be ok. Btw, the ndk version I used is r14b.
wish it helps.
