### ISSUE TITLE
Ask about source path.

### ISSUE THREAD

**Issue by yuri4029** [FangGet/pangolin_android#4]
Hi FangGet, I'am on project which use pangolin with android. In your tut, I don't know what is source path ? May be it is the link to Cmakelist.txt of pangolin ? Thanks.

**Comment by FangGet** [comment]
if you run cmake at build directory, then replace source_path to  .. , point to its parent directory

**Comment by yuri4029** [comment]
very thanks your reply, when I replace source_path to .. , this happened.
![source_path](https://user-images.githubusercontent.com/23437453/36528889-3d6eb5ea-17e9-11e8-84d2-353f3f98c686.png)

**Comment by FangGet** [comment]
Try change .. to ../Pangolin

**Comment by yuri4029** [comment]
Thanks you help. I tried ../Pangolin but it will better if use directory path like /home/tran_minh/Pangolin.
When I used it, had some error and I don't know why.
![toolchain_and_cmake_error](https://user-images.githubusercontent.com/23437453/36530992-2276c790-17ef-11e8-9dde-c9a3823dd86b.png)

**Comment by FangGet** [comment]
You should learn something about cmake first. Path is not right for your compile

**Comment by yuri4029** [comment]
Yes, I am very new with Cmake, and very confuse with these stuffs. Can you give me some recommendations for cmake, or what should I do next ? Very thank you. If I am so naive, please forgive me.

**Comment by FangGet** [comment]
cmake tutorial just fine, have a try!
