### ISSUE TITLE
How to compile file lib.so ?

### ISSUE THREAD

**Issue by yuri4029** [FangGet/pangolin_android#5]
Hi FangGet, I read about Cmake and I downloaded your code on baidu cloud, so now I try to compile libpangolin.so and I did these things:
1. I use building script (at FangGet repo) on build.gardle like this 
![build gardle](https://user-images.githubusercontent.com/23437453/36681611-af7f5e54-1b4b-11e8-9463-f0f15c468bb7.png)
2. I changed CMakeList.txt  and add 2 files HelloPangolin_shared_load.h and HelloPangolin_start.cpp 
![cmakelist](https://user-images.githubusercontent.com/23437453/36681657-cea42968-1b4b-11e8-895d-9edcfffe6b06.png)
after that, I built it to an apk app, but it cannot run (stopped working), and I realized that may be because file lib.so  hasn't  had any data, you can see here, file lib.so has been built but its size is only 5kb, (your lib.so at your example is > 4 mb)
![lib so](https://user-images.githubusercontent.com/23437453/36681822-3f6e626c-1b4c-11e8-9043-0634c720a7fe.png)

Can you give me some advise please ?

**Comment by FangGet** [comment]
do you want to generate libpangolin.so so just use this lib to generate other apps? To generate libpangolin.so, you can use linux+cmake+ndk refer to ReadMe . To generate your own lib.so at Android Studio, please refer to [http://tools.android.com/tech-docs/external-c-builds](http://tools.android.com/tech-docs/external-c-builds)

**Comment by yuri4029** [comment]
Thanks your reply, I just want to generate it, so I can run a project like hellopangolin and create an apk app .
By the way, when I run your pangolin_android, I caught a problem with api-level.h, please give me advise .
![api_level](https://user-images.githubusercontent.com/23437453/36784225-4afc9f48-1cb1-11e8-9da5-0ab33641d845.png)
